version: "4.0"
services:
  app:
    container_name: oatsoutpost-home
    restart: always
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERID: 0
        GROUPID: 0
    ports:
      - '3000:3000'
networks:
  default:
    name: proxynet
    external: true
